### ISSUE TITLE
Error parsing saved session

### ISSUE THREAD

**Issue by nicolabressan** [iadgov/GRASSMARLIN#20]
Hello,
i'm using grassmarlin 3.2.1 on Windows 10, x64 version.
I've imported several .pcap files and saved the session into a gm3 file, just to avoid re-importing again those pcap files next time.
When I try to open that session again I get a "Error parsing session information" in grassmarlin message console and the logical view is empty.

This is the output of the dos window:

```
Exception in thread "JavaFX Application Thread" java.lang.IndexOutOfBoundsException: Index: 46, Size: 0
        at java.util.ArrayList.rangeCheck(Unknown Source)
        at java.util.ArrayList.get(Unknown Source)
        at core.document.serialization.Grassmarlin_3_2.layoutGraphNode(Grassmarlin_3_2.java:1220)
        at core.document.serialization.Grassmarlin_3_2$TabLoadHandler.endElement(Grassmarlin_3_2.java:1096)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(Unknown Source)
        at core.document.serialization.Grassmarlin_3_2.loadTab(Grassmarlin_3_2.java:924)
        at core.document.serialization.Grassmarlin_3_2.lambda$loadDocumentSax$306(Grassmarlin_3_2.java:132)
        at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
        at java.lang.Thread.run(Unknown Source)
```

any help?

**Comment by iadgovuser22** [comment]
Hi,

This is a known issue in 3.2.1. Have you tried using 3.2.0 to save/restore a session?

Thanks
